server:
  port: 8888  # 服务端口

spring:
  application:
    # 服务名
    name: service
  datasource:
    # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://calvities.cn:3306/test_new_project?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: cl520.
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis日志
mybatis-plus:
  # 此注释为逻辑删除的配置，但是在V_3.3.0 配置后可以忽略不配置步骤
#  global-config:
#    db-config:
#      ogic-delete-field: deleted # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 状态 1 表示已删除
#      logic-not-delete-value: 0 # 状态 0 表示未删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置日志级别
logging:
  level:
    root: INFO